# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbcb515a327095f345b8970e9b7e55427f4f2395cb85d7462ad77d55cbc75d44770b81cf561f7054bd412d899fd8b008d3a13f1e16e83e8cd458546ff6a5b7ab

test:
  secret_key_base: 16d7e478bbb4029e1137c8f1194db9a0e56b98493134d7866ce222a00b939a84a187859b705f0a9d0297ac92c03aa9aa05504ec3c7be3c6daa81e8ad89b68d27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
